services:
  gradetrack:
    build: .
    image: gradetrack
    container_name: gradetrack
    environment:
      - DISPLAY=${DISPLAY}
      - QT_QPA_PLATFORM=xcb
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config:/app/config
      - ./data:/app/data
    stdin_open: true
    tty: true
